export const Action = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    CONFIG_INIT: 'CONFIG_INIT',

    ACCOUNT_LIST_INIT: 'ACCOUNT_LIST_INIT',
    ACCOUNT_LIST_LOADING: 'ACCOUNT_LIST_LOADING',
    ACCOUNT_SEARCH_CHANGE: 'ACCOUNT_SEARCH_CHANGE',
    ACCOUNT_PAGE_CHANGE: 'ACCOUNT_PAGE_CHANGE',
    ACCOUNT_SIZE_CHANGE: 'ACCOUNT_SIZE_CHANGE',

    PERMISSION_LIST_INIT: 'PERMISSION_LIST_INIT',
    PERMISSION_LIST_LOADING: 'PERMISSION_LIST_LOADING',
    PERMISSION_PAGE_CHANGE: 'PERMISSION_PAGE_CHANGE',
    PERMISSION_SIZE_CHANGE: 'PERMISSION_SIZE_CHANGE',

    ACTIVITY_LIST_INIT: 'ACTIVITY_LIST_INIT',
    ACTIVITY_LIST_LOADING: 'ACTIVITY_LIST_LOADING',
    ACTIVITY_SEARCH_CHANGE: 'ACTIVITY_SEARCH_CHANGE',
    ACTIVITY_PAGE_CHANGE: 'ACTIVITY_PAGE_CHANGE',
    ACTIVITY_SIZE_CHANGE: 'ACTIVITY_SIZE_CHANGE',

    //Users
    USERS_LOADING: 'USERS_LOADING',
    USERS_SEARCH: 'USERS_SEARCH',
    USERS_ACTIVE: 'USERS_ACTIVE',

    PROPERTY_LIST_INIT: 'PROPERTY_LIST_INIT',
    PROPERTY_LIST_LOADING: 'PROPERTY_LIST_LOADING',
    PROPERTY_SEARCH_CHANGE: 'PROPERTY_SEARCH_CHANGE',
    PROPERTY_DATE_CHANGE: 'PROPERTY_DATE_CHANGE',
    PROPERTY_PAGE_CHANGE: 'PROPERTY_PAGE_CHANGE',
    PROPERTY_SIZE_CHANGE: 'PROPERTY_SIZE_CHANGE',

    AUCTION_LIST_INIT: 'AUCTION_LIST_INIT',
    AUCTION_LIST_LOADING: 'AUCTION_LIST_LOADING',
    AUCTION_SEARCH_CHANGE: 'AUCTION_SEARCH_CHANGE',
    AUCTION_DATE_CHANGE: 'AUCTION_DATE_CHANGE',
    AUCTION_PAGE_CHANGE: 'AUCTION_PAGE_CHANGE',
    AUCTION_SIZE_CHANGE: 'AUCTION_SIZE_CHANGE',

    AUCTION_HISTORICAL_LIST_INIT: 'AUCTION_HISTORICAL_LIST_INIT',
    AUCTION_HISTORICAL_LIST_LOADING: 'AUCTION_HISTORICAL_LIST_LOADING',
    AUCTION_HISTORICAL_SEARCH_CHANGE: 'AUCTION_HISTORICAL_SEARCH_CHANGE',
    AUCTION_HISTORICAL_DATE_CHANGE: 'AUCTION_HISTORICAL_DATE_CHANGE',
    AUCTION_HISTORICAL_PAGE_CHANGE: 'AUCTION_HISTORICAL_PAGE_CHANGE',
    AUCTION_HISTORICAL_SIZE_CHANGE: 'AUCTION_HISTORICAL_SIZE_CHANGE',

    USER_REGISTER_AUCTION_LOADING: 'USER_REGISTER_AUCTION_LOADING',
    USER_REGISTER_AUCTION_LIST: 'USER_REGISTER_AUCTION_LIST',
}